/* tslint:disable */


/**
 * AUTO-GENERATED FILE @ 2020-01-31 18:12:34 - DO NOT EDIT!
 *
 * This file was automatically generated by schemats v.3.0.3
 * $ schemats generate -c postgres://username:password@localhost:6666/infrarays_test -t knex_migrations -t surveys -t backemail -t emails -t users -t tokens -t sessions -t admins -t files -t knex_migrations_lock -s public
 *
 */


export namespace knex_migrationsFields {
    export type id = number;
    export type name = string | null;
    export type batch = number | null;
    export type migration_time = Date | null;

}

export interface knex_migrations {
    id: knex_migrationsFields.id;
    name: knex_migrationsFields.name;
    batch: knex_migrationsFields.batch;
    migration_time: knex_migrationsFields.migration_time;

}

export namespace surveysFields {
    export type id = string;
    export type user_id = string;
    export type city = string;
    export type school = string;
    export type gender = string;
    export type application_portal = number;
    export type application_process = number;
    export type improvement = string;
    export type informant = string;

}

export interface surveys {
    id: surveysFields.id;
    user_id: surveysFields.user_id;
    city: surveysFields.city;
    school: surveysFields.school;
    gender: surveysFields.gender;
    application_portal: surveysFields.application_portal;
    application_process: surveysFields.application_process;
    improvement: surveysFields.improvement;
    informant: surveysFields.informant;

}

export namespace backemailFields {
    export type type = string;
    export type content = string;

}

export interface backemail {
    type: backemailFields.type;
    content: backemailFields.content;

}

export namespace emailsFields {
    export type type = string;
    export type content = string;

}

export interface emails {
    type: emailsFields.type;
    content: emailsFields.content;

}

export namespace usersFields {
    export type id = string;
    export type email = string;
    export type password = string;
    export type name = string;
    export type birthdate = Date;
    export type finnish = boolean;
    export type recommendations = Array<Object>;
    export type verified = boolean;

}

export interface users {
    id: usersFields.id;
    email: usersFields.email;
    password: usersFields.password;
    name: usersFields.name;
    birthdate: usersFields.birthdate;
    finnish: usersFields.finnish;
    recommendations: usersFields.recommendations;
    verified: usersFields.verified;

}

export namespace tokensFields {
    export type id = string;
    export type type = string;
    export type user_id = string;

}

export interface tokens {
    id: tokensFields.id;
    type: tokensFields.type;
    user_id: tokensFields.user_id;

}

export namespace sessionsFields {
    export type sid = string;
    export type sess = Object;
    export type expired = Date;

}

export interface sessions {
    sid: sessionsFields.sid;
    sess: sessionsFields.sess;
    expired: sessionsFields.expired;

}

export namespace adminsFields {
    export type id = string;
    export type email = string;
    export type password = string;
    export type name = string;
    export type super_admin = boolean;

}

export interface admins {
    id: adminsFields.id;
    email: adminsFields.email;
    password: adminsFields.password;
    name: adminsFields.name;
    super_admin: adminsFields.super_admin;

}

export namespace filesFields {
    export type id = string;
    export type user_id = string;
    export type type = string;
    export type created = Date;
    export type file_name = string;
    export type file = Buffer;

}

export interface files {
    id: filesFields.id;
    user_id: filesFields.user_id;
    type: filesFields.type;
    created: filesFields.created;
    file_name: filesFields.file_name;
    file: filesFields.file;

}

export namespace knex_migrations_lockFields {
    export type index = number;
    export type is_locked = number | null;

}

export interface knex_migrations_lock {
    index: knex_migrations_lockFields.index;
    is_locked: knex_migrations_lockFields.is_locked;

}
