/* tslint:disable */

/**
 * AUTO-GENERATED FILE @ 2020-01-27 21:48:45 - DO NOT EDIT!
 *
 * This file was automatically generated by schemats v.3.0.3
 * $ schemats generate -c postgres://username:password@localhost:6666/infrarays_test -t knex_migrations -t emails -t tokens -t users -t sessions -t admins -t files -t knex_migrations_lock -s public
 *
 */

export namespace knex_migrationsFields {
    export type id = number;
    export type name = string | null;
    export type batch = number | null;
    export type migration_time = Date | null;

}

export interface knex_migrations {
    id: knex_migrationsFields.id;
    name: knex_migrationsFields.name;
    batch: knex_migrationsFields.batch;
    migration_time: knex_migrationsFields.migration_time;

}

export namespace emailsFields {
    export type type = string;
    export type content = string;

}

export interface emails {
    type: emailsFields.type;
    content: emailsFields.content;

}

export namespace tokensFields {
    export type id = string;
    export type type = string;
    export type user_id = string;

}

export interface tokens {
    id: tokensFields.id;
    type: tokensFields.type;
    user_id: tokensFields.user_id;

}

export namespace usersFields {
    export type id = string;
    export type email = string;
    export type password = string;
    export type name = string;
    export type birthdate = Date;
    export type finnish = boolean;
    export type recommendations = Array<Object>;
    export type verified = boolean;

}

export interface users {
    id: usersFields.id;
    email: usersFields.email;
    password: usersFields.password;
    name: usersFields.name;
    birthdate: usersFields.birthdate;
    finnish: usersFields.finnish;
    recommendations: usersFields.recommendations;
    verified: usersFields.verified;

}

export namespace sessionsFields {
    export type sid = string;
    export type sess = Object;
    export type expired = Date;

}

export interface sessions {
    sid: sessionsFields.sid;
    sess: sessionsFields.sess;
    expired: sessionsFields.expired;

}

export namespace adminsFields {
    export type id = string;
    export type email = string;
    export type password = string;
    export type name = string;
    export type super_admin = boolean | null;

}

export interface admins {
    id: adminsFields.id;
    email: adminsFields.email;
    password: adminsFields.password;
    name: adminsFields.name;
    super_admin: adminsFields.super_admin;

}

export namespace filesFields {
    export type id = string;
    export type user_id = string;
    export type type = string;
    export type file = Buffer | null;

}

export interface files {
    id: filesFields.id;
    user_id: filesFields.user_id;
    type: filesFields.type;
    file: filesFields.file;

}

export namespace knex_migrations_lockFields {
    export type index = number;
    export type is_locked = number | null;

}

export interface knex_migrations_lock {
    index: knex_migrations_lockFields.index;
    is_locked: knex_migrations_lockFields.is_locked;

}
